import { MandiRecord, Scheme } from '../types';

export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 1,
    title: "Pradhan Mantri Fasal Bima Yojana (PMFBY)",
    description: "Crop insurance scheme to provide financial support to farmers suffering crop loss/damage due to unforeseen events.",
    category: "Insurance",
    crops: ["All Food Crops", "Oilseeds"],
    link: "#"
  },
  {
    id: 2,
    title: "PM Kisan Samman Nidhi",
    description: "Income support of ₹6,000 per year to all landholding farmer families.",
    category: "Subsidy",
    crops: ["All"],
    link: "#"
  },
  {
    id: 3,
    title: "Soil Health Card Scheme",
    description: "Provides information to farmers on nutrient status of their soil along with recommendations on appropriate dosage of nutrients.",
    category: "Training",
    crops: ["All"],
    link: "#"
  },
  {
    id: 4,
    title: "Kisan Credit Card (KCC)",
    description: "Adequate and timely credit support from the banking system under a single window.",
    category: "Loan",
    crops: ["All"],
    link: "#"
  },
  {
    id: 5,
    title: "National Horticulture Mission",
    description: "Promotes holistic growth of the horticulture sector through area based regionally differentiated strategies.",
    category: "Subsidy",
    crops: ["Fruits", "Vegetables", "Flowers"],
    link: "#"
  }
];

export const MOCK_MANDI_DATA: MandiRecord[] = [
  { id: 1, state: "Bihar", district: "Bhojpur", market: "Piro", crop: "Onion", variety: "Medium", grade: "FAQ", date: "07/06/2024", minPrice: 1850, maxPrice: 1900, price: 1875, trend: "up" },
  { id: 2, state: "Bihar", district: "Bhojpur", market: "Piro", crop: "Potato", variety: "Jyoti", grade: "FAQ", date: "07/06/2024", minPrice: 2500, maxPrice: 2550, price: 2525, trend: "up" },
  { id: 3, state: "Bihar", district: "Madhubani", market: "Jainagar", crop: "Onion", variety: "Medium", grade: "FAQ", date: "07/06/2024", minPrice: 2300, maxPrice: 2500, price: 2400, trend: "up" },
  { id: 4, state: "Bihar", district: "Vaishali", market: "Jaitipir Mandi", crop: "Potato", variety: "Jyoti", grade: "FAQ", date: "07/06/2024", minPrice: 2850, maxPrice: 3000, price: 2900, trend: "up" },
  { id: 5, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Bhindi(Ladies Finger)", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3500, trend: "stable" },
  { id: 6, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Brinjal", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3500, trend: "stable" },
  { id: 7, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Cabbage", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 1000, maxPrice: 2000, price: 1500, trend: "down" },
  { id: 8, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Capsicum", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3500, trend: "stable" },
  { id: 9, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Cauliflower", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 6000, maxPrice: 7000, price: 6500, trend: "up" },
  { id: 10, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Guar", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 9000, maxPrice: 10000, price: 9500, trend: "up" },
  { id: 11, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Lemon", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3500, trend: "down" },
  { id: 12, state: "Gujarat", district: "Morbi", market: "Vankaner(Sub yard)", crop: "Tomato", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3500, trend: "stable" },
  { id: 13, state: "Gujarat", district: "Narmada", market: "Rajpipla", crop: "Arhar (Tur/Red Gram)", variety: "777 New Ind", grade: "FAQ", date: "07/06/2024", minPrice: 7600, maxPrice: 8765, price: 8325, trend: "up" },
  { id: 14, state: "Gujarat", district: "Narmada", market: "Rajpipla", crop: "Banana", variety: "Other", grade: "Large", date: "07/06/2024", minPrice: 1500, maxPrice: 2400, price: 1800, trend: "stable" },
  { id: 15, state: "Haryana", district: "Sirsa", market: "Ellanabad", crop: "Bengal Gram", variety: "Desi (Whole)", grade: "FAQ", date: "07/06/2024", minPrice: 6800, maxPrice: 6860, price: 6850, trend: "up" },
  { id: 16, state: "Haryana", district: "Sirsa", market: "Ellanabad", crop: "Cotton", variety: "American", grade: "FAQ", date: "07/06/2024", minPrice: 6110, maxPrice: 6800, price: 6190, trend: "stable" },
  { id: 17, state: "Haryana", district: "Sirsa", market: "Ellanabad", crop: "Guar", variety: "Gwar", grade: "FAQ", date: "07/06/2024", minPrice: 3500, maxPrice: 5124, price: 5050, trend: "down" },
  { id: 18, state: "Haryana", district: "Sirsa", market: "Ellanabad", crop: "Mustard", variety: "Mustard", grade: "FAQ", date: "07/06/2024", minPrice: 5526, maxPrice: 5526, price: 5526, trend: "stable" },
  { id: 19, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Apple", variety: "Apple", grade: "Medium", date: "07/06/2024", minPrice: 11000, maxPrice: 12000, price: 11500, trend: "up" },
  { id: 20, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Apricot", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 6000, maxPrice: 7000, price: 6500, trend: "stable" },
  { id: 21, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Banana", variety: "Banana - Ripe", grade: "Medium", date: "07/06/2024", minPrice: 3000, maxPrice: 4200, price: 3800, trend: "up" },
  { id: 22, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Beetroot", variety: "Beetroot", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 4000, price: 3600, trend: "stable" },
  { id: 23, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Bhindi", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2500, maxPrice: 2800, price: 2700, trend: "stable" },
  { id: 24, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Bitter gourd", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2500, maxPrice: 3000, price: 2800, trend: "stable" },
  { id: 25, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Bottle gourd", variety: "Bottle Gourd", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2300, trend: "down" },
  { id: 26, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Brinjal", variety: "Brinjal", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2300, trend: "stable" },
  { id: 27, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Cabbage", variety: "Cabbage", grade: "FAQ", date: "07/06/2024", minPrice: 1600, maxPrice: 1800, price: 1700, trend: "down" },
  { id: 28, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Capsicum", variety: "Capsicum", grade: "FAQ", date: "07/06/2024", minPrice: 3500, maxPrice: 4000, price: 3800, trend: "up" },
  { id: 29, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Carrot", variety: "Carrot", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2300, trend: "stable" },
  { id: 30, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Cauliflower", variety: "Cauliflower", grade: "FAQ", date: "07/06/2024", minPrice: 2200, maxPrice: 3000, price: 2750, trend: "up" },
  { id: 31, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Colacasia", variety: "Colacasia", grade: "FAQ", date: "07/06/2024", minPrice: 4000, maxPrice: 5000, price: 4500, trend: "up" },
  { id: 32, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Coriander", variety: "Coriander", grade: "FAQ", date: "07/06/2024", minPrice: 10000, maxPrice: 12000, price: 11500, trend: "up" },
  { id: 33, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Cucumbar", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 3000, price: 2700, trend: "stable" },
  { id: 34, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "French Beans", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 6500, maxPrice: 7000, price: 6800, trend: "up" },
  { id: 35, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Garlic", variety: "Average", grade: "FAQ", date: "07/06/2024", minPrice: 14000, maxPrice: 15000, price: 14600, trend: "up" },
  { id: 36, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Ginger", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 16000, maxPrice: 17000, price: 16700, trend: "up" },
  { id: 37, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Grapes", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 8000, maxPrice: 10000, price: 9000, trend: "stable" },
  { id: 38, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Green Chilli", variety: "Green Chilly", grade: "FAQ", date: "07/06/2024", minPrice: 3000, maxPrice: 3500, price: 3350, trend: "stable" },
  { id: 39, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Guava", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 8000, maxPrice: 9000, price: 8700, trend: "up" },
  { id: 40, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Karbuja", variety: "Karbhuja", grade: "Medium", date: "07/06/2024", minPrice: 1800, maxPrice: 3000, price: 2500, trend: "stable" },
  { id: 41, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Lemon", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 7500, maxPrice: 8000, price: 7800, trend: "up" },
  { id: 42, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Mango", variety: "Dusheri", grade: "Medium", date: "07/06/2024", minPrice: 5000, maxPrice: 6000, price: 5500, trend: "stable" },
  { id: 43, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Mango", variety: "Safeda", grade: "Medium", date: "07/06/2024", minPrice: 9000, maxPrice: 10000, price: 9700, trend: "up" },
  { id: 44, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Mango", variety: "Totapuri", grade: "Medium", date: "07/06/2024", minPrice: 6000, maxPrice: 6500, price: 6300, trend: "stable" },
  { id: 45, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Mushrooms", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 3000, price: 2500, trend: "down" },
  { id: 46, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Mousambi", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 6000, maxPrice: 7000, price: 6500, trend: "stable" },
  { id: 47, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Onion", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2400, maxPrice: 2500, price: 2450, trend: "up" },
  { id: 48, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Papaya", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 4000, maxPrice: 4500, price: 4350, trend: "stable" },
  { id: 49, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Peas Wet", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 5000, maxPrice: 5500, price: 5300, trend: "down" },
  { id: 50, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Pineapple", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 5000, maxPrice: 5500, price: 5300, trend: "stable" },
  { id: 51, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Pomegranate", variety: "Other", grade: "Medium", date: "07/06/2024", minPrice: 10000, maxPrice: 15000, price: 11000, trend: "up" },
  { id: 52, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Potato", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2200, maxPrice: 2400, price: 2300, trend: "stable" },
  { id: 53, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Pumpkin", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 1000, maxPrice: 1200, price: 1100, trend: "down" },
  { id: 54, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Raddish", variety: "Raddish", grade: "FAQ", date: "07/06/2024", minPrice: 2500, maxPrice: 3000, price: 2800, trend: "stable" },
  { id: 55, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Spinach", variety: "Spinach", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2300, trend: "stable" },
  { id: 56, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Sponge gourd", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2300, trend: "stable" },
  { id: 57, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Tinda", variety: "Tinda", grade: "FAQ", date: "07/06/2024", minPrice: 2000, maxPrice: 2500, price: 2350, trend: "stable" },
  { id: 58, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Tomato", variety: "Tomato", grade: "FAQ", date: "07/06/2024", minPrice: 1200, maxPrice: 1400, price: 1350, trend: "down" },
  { id: 59, state: "Himachal Pradesh", district: "Kangra", market: "Palampur", crop: "Water Melon", variety: "Other", grade: "Large", date: "07/06/2024", minPrice: 1200, maxPrice: 1500, price: 1350, trend: "stable" },
  { id: 60, state: "Karnataka", district: "Raichur", market: "Lingasugur", crop: "Bajra", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 2120, maxPrice: 2620, price: 2580, trend: "up" },
  { id: 61, state: "Karnataka", district: "Raichur", market: "Lingasugur", crop: "Maize", variety: "Hybrid/Local", grade: "FAQ", date: "07/06/2024", minPrice: 2300, maxPrice: 2300, price: 2300, trend: "stable" },
  { id: 62, state: "Karnataka", district: "Raichur", market: "Lingasugur", crop: "Paddy", variety: "Sona", grade: "FAQ", date: "07/06/2024", minPrice: 2500, maxPrice: 2500, price: 2500, trend: "stable" },
  { id: 63, state: "Kerala", district: "Alappuzha", market: "Harippad", crop: "Amaranthus", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 4000, maxPrice: 4500, price: 4000, trend: "stable" },
  { id: 64, state: "Kerala", district: "Alappuzha", market: "Harippad", crop: "Banana", variety: "Nendra Bale", grade: "Medium", date: "07/06/2024", minPrice: 5000, maxPrice: 5500, price: 5000, trend: "up" },
  { id: 65, state: "Kerala", district: "Kannur", market: "Kannur", crop: "Black pepper", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 57000, maxPrice: 62000, price: 60000, trend: "up" },
  { id: 66, state: "Kerala", district: "Kannur", market: "Kannur", crop: "Coconut Oil", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 16400, maxPrice: 17500, price: 17000, trend: "up" },
  { id: 67, state: "Madhya Pradesh", district: "Indore", market: "Indore", crop: "Garlic", variety: "Garlic", grade: "FAQ", date: "07/06/2024", minPrice: 7010, maxPrice: 7010, price: 7010, trend: "up" },
  { id: 68, state: "Madhya Pradesh", district: "Indore", market: "Indore", crop: "Wheat", variety: "Local", grade: "FAQ", date: "07/06/2024", minPrice: 2480, maxPrice: 2480, price: 2480, trend: "stable" },
  { id: 69, state: "Odisha", district: "Sundergarh", market: "Panposh", crop: "Brinjal", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 1600, maxPrice: 2000, price: 1900, trend: "stable" },
  { id: 70, state: "Punjab", district: "Amritsar", market: "Rayya", crop: "Onion", variety: "Red", grade: "FAQ", date: "07/06/2024", minPrice: 1800, maxPrice: 1800, price: 1800, trend: "stable" },
  { id: 71, state: "Punjab", district: "Amritsar", market: "Rayya", crop: "Potato", variety: "Other", grade: "FAQ", date: "07/06/2024", minPrice: 700, maxPrice: 700, price: 700, trend: "down" },
  { id: 72, state: "Rajasthan", district: "Chittorgarh", market: "Kapasan", crop: "Wheat", variety: "Lokwan", grade: "FAQ", date: "07/06/2024", minPrice: 2400, maxPrice: 2600, price: 2500, trend: "up" },
  { id: 73, state: "Rajasthan", district: "Rajasamand", market: "Rajsamand", crop: "Potato", variety: "Potato", grade: "FAQ", date: "07/06/2024", minPrice: 1400, maxPrice: 1600, price: 1500, trend: "up" },
  { id: 74, state: "Telangana", district: "Khammam", market: "Dammapet", crop: "Paddy", variety: "1001", grade: "FAQ", date: "07/06/2024", minPrice: 2200, maxPrice: 2202, price: 2201, trend: "stable" },
  { id: 75, state: "Uttar Pradesh", district: "Baghpat", market: "Baraut", crop: "Apple", variety: "Kasmir/Shimla - II", grade: "Medium", date: "07/06/2024", minPrice: 9400, maxPrice: 9500, price: 9450, trend: "up" },
  { id: 76, state: "Uttar Pradesh", district: "Baghpat", market: "Baraut", crop: "Mango", variety: "Dusheri", grade: "Medium", date: "07/06/2024", minPrice: 5000, maxPrice: 5500, price: 5200, trend: "up" },
  { id: 77, state: "Uttar Pradesh", district: "Hathras", market: "Haathras", crop: "Potato", variety: "Desi", grade: "FAQ", date: "07/06/2024", minPrice: 1500, maxPrice: 1700, price: 1640, trend: "stable" }
];